services:
  web:
    build: ./app
    ports:
      - "8000:5000"
    volumes:
      - ./app:/code
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
